name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:


env:
   S3_BUCKET_NAME: kod-springboot-build
   PROJECT_NAME: kod-springboot-webservice



jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 1.8

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        shell: bash

      - name: Build with Gradle
        run: ./gradlew clean build
        shell: bash

      - name: Get current time
        uses: 1466587594/get-current-time@v2
        id: current-time
        with:
          format: YYYY-MM-DDTHH-mm-ss
          utcOffset: "+09:00"

      - name: Show Current Time
        run: echo "CurrentTime=${{steps.current-time.outputs.formattedTime}}"
        shell: bash
      #기존 zip -r kod-springboot-webservice *
      - name: Make zip file
        run:
          mkdir -p before-deploy # zip에 포함시킬 파일들을 담을 디렉토리 생성
          cp scripts/*.sh before-deploy/
          cp appspec.yml before-deploy/
          cp build/libs/*.jar before-deploy/
          cd before-deploy && zip -r before-deploy * # before-deploy로 이동후 전체 압축
          cd ../ && mkdir -p deploy # 상위 디렉토리로 이동후 deploy 디렉토리 생성
          mv before-deploy/before-deploy.zip deploy/kod-springboot-webservice.zip # deploy로 zip파일 이동
        shell: bash

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Upload to S3
        run: aws s3 cp --region ap-northeast-2 deploy/kod-springboot-webservice.zip s3://$S3_BUCKET_NAME/$PROJECT_NAME/kod-springboot-webservice.zip

      - name: Code Deploy
        run: aws deploy create-deployment --application-name kod-springboot-webservice --deployment-config-name CodeDeployDefault.AllAtOnce --deployment-group-name kod-springboot-webservice-group --s3-location bucket=$S3_BUCKET_NAME,bundleType=zip,key=$PROJECT_NAME/kod-springboot-webservice.zip




